apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grayground
  name: grayground-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: grayground
  type: LoadBalancer
status:
  loadBalancer: {}
